name: map_integration
description: "A new Flutter project integrating Google Maps and geofencing."

publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.0 # Add the Google Maps Flutter plugin
  geolocator: ^9.0.2        # Add the Geolocator plugin for location services

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
